name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Test
      run: mvn clean install
    - name: Report
      uses: dorny/test-reporter@v1.7.0
      if: always()
      with:
        name: Unit Tests
        path: "**/target/surefire-reports/*.xml"
        reporter: java-junit
        fail-on-error: true
